### ISSUE TITLE
gpg: no valid OpenPGP data found. on setup_docker

### ISSUE THREAD

**Issue by llermaly** [o19s/quepid#430] opened 2021-10-13 03:42 UTC
**Describe the bug**
When I try to run ./bin/setup_docker an error with yarn gpg key appears.

**To Reproduce**
1. run ./bin/setup_docker

**Expected behavior**
App building

**Additional context**
I have a macbook pro M1, maybe thats the issue? looked up in the issues without success/

This is the error

```
Step 10/14 : RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
 ---> Running in d305904be3b4
Warning: apt-key output should not be parsed (stdout is not a terminal)
Segmentation fault
gpg: no valid OpenPGP data found.
ERROR: Service 'app' failed to build : The command '/bin/sh -c curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -' returned a non-zero code: 2
```

**Comment by epugh** [comment] 2021-10-14 11:56
We have figured out how to run the *Production* version of Quepid on M1, please see details here: https://github.com/o19s/quepid/wiki/Installation-Guide#quepid-using-macos-on-apple-silicon-m1-chip

However, this remains a head scratcher...   I don't really know what the issue is, and since I'm not on M1 (at least till Q2 of 2022!), I can't really debug it.....   

If you google about and find some ideas, I'd LOVE to hear them.

**Comment by o19s-admin** [comment] 2022-01-24 13:16
Actually the fix for apple silicon also fixes this, need to link issue to
pr

**Comment by epugh** [comment] 2022-02-17 12:24
Okay, going to close this, it's fixed.   @llermaly please reopen if the fix isn't working for you!

**Closed by epugh** 2022-02-17 12:24 UTC
